### ISSUE TITLE
When will the service return?

### ISSUE THREAD

**Issue by bobbie7wei1998** [aws/studio-lab-examples#153] opened 2022-11-02 08:05 UTC
When will the service return? 

![image](https://user-images.githubusercontent.com/111459190/199433553-b1c4c4c1-70b3-4652-ba9a-1fc5551845c3.png)

**Comment by icoxfog417** [comment] 2022-11-02 13:17
@bobbie7wei1998 Sorry for the unavailability of the Studio Lab. Service team is working to solve the issue. We can not answer the time line but we will notify you after the issue is solved.

**Comment by MicheleMonclova** [comment] 2022-11-02 15:42
Hi, the system has been restored for CPU - but we will keep this message up until it has been restored for GPU as well.

**Comment by bobbie7wei1998** [comment] 2022-11-02 21:07
Thank you so much
Thanks to the service team

**Comment by aozorahime** [comment] 2022-11-03 06:08
I cant use the CPU either. does the problem also affect the cpu?

**Comment by MicheleMonclova** [comment] 2022-11-04 17:30
This problem did effect CPU - but all should be fine now.

**Comment by icoxfog417** [comment] 2022-11-05 05:45
Thank you for your great patience for service unavailability. We confirmed to engineering team, and the service is back now.

I close this issue because the problem is solved. If you have the other trouble, please raise another issue.

**Closed by icoxfog417** 2022-11-05 05:45 UTC
Labels: bug
