### ISSUE TITLE
Unable to open database file, Unexpected error while saving file: d2l-pytorch-sagemaker-studio-lab/dash/Untitled.ipynb unable to open database file

### ISSUE THREAD

**Issue by someshfengde** [aws/studio-lab-examples#94] opened 2022-03-22 19:52 UTC
**Describe the bug**
![image](https://user-images.githubusercontent.com/42097653/159563812-a9471c23-ad6a-4354-9e30-ef001df04352.png)

**To Reproduce**
I've deleted some of the unwanted notebooks from studio lab's files and now I am getting this error. 
cannot install libraries with pip, cannot create new files, cannot even start kernel

**Comment by lorazabora** [comment] 2022-03-23 01:34
Hey there, I’m not one of the devs sorry

But i wanna ask if you can start up a GPU runtime? Kindly Try and let me know thanks

**Comment by someshfengde** [comment] 2022-03-23 05:18
@lorazabora  while launching the GPU instance I am getting this as there is no runtime environment available available right now 
![image](https://user-images.githubusercontent.com/42097653/159628994-38b1c339-ac43-4f6a-8ac7-56f32a8174f9.png)

**Comment by lorazabora** [comment] 2022-03-24 00:49
So then indeed everyone is experiencing the same issue

It’s been over a week now and not yet fixed, CPU runtimes aren’t enough for my workloads neither that they even make much sense since there’s already many free cloud CPU options out there

I hope they see and fix this soon

**Comment by icoxfog417** [comment] 2022-03-24 08:18
@someshfengde Thank you for reporting the problem. Would you please tell us how did you delete the notebooks? Because only delete the specific files does not affect the behavior of Jupyter Lab. We need to know the procedure to reproduce your problem.

If you need the Studio Lab as soon as possible, recreate the account is one of the option.

**Comment by someshfengde** [comment] 2022-03-30 12:41
Yes I tried to delete all notebooks from directory maybe because of that

How can I recreate account?

**Comment by icoxfog417** [comment] 2022-03-30 13:00
@someshfengde You can delete the account from here.

![image](https://user-images.githubusercontent.com/544269/160840123-5f628318-f158-4e40-abba-29524ceb4248.png)

**Comment by icoxfog417** [comment] 2022-06-18 22:10
Dear @someshfengde , to delete the account was worked for you? If you still have problem, please let us know. If you already solved the problem, please let us know by closing the this issue.

**Comment by someshfengde** [comment] 2022-06-19 08:22
Hi @icoxfog417  I resolved the issue by deleting and opening the account again .
 Thanks for your response :smile:  closing issue now :)

**Closed** 2022-06-19 08:23 UTC
Labels: bug

**Comment by icoxfog417** [comment] 2022-06-19 22:04
You are welcome! We are very glad if Studio Lab supports your data science learning.
