### ISSUE TITLE
we are experiencing elevated fault rate in start runtime API. The SageMaker Studio Lab team is working to restore the service.

### ISSUE THREAD

**Issue by saleemmalik10835** [aws/studio-lab-examples#155] opened 2022-11-03 01:14 UTC
its been more than 3 days and im still getting this issue, i cant run cpu or even gpu runtimes in sagemaker
how long is this going to even take man

**Comment by aozorahime** [comment] 2022-11-03 06:10
up

**Comment by saleemmalik10835** [comment] 2022-11-03 06:52
Ah finally

**Comment by aozorahime** [comment] 2022-11-04 02:30
btw, I can run the CPU but not GPU today

**Comment by icoxfog417** [comment] 2022-11-05 05:51
@saleemmalik10835 Sorry for the long inconvenience of Studio Lab. As you know, the service was back and we confirmed that we can say it to you. I will close this issue because the mentioned problem is solved.

But as @aozorahime said, the GPU instance is sometime unavailable because of another instance allocation issue. Of course, we deal with this problem now.

**Closed by icoxfog417** 2022-11-05 05:51 UTC
Labels: bug
