### ISSUE TITLE
Bug request new account

### ISSUE THREAD

**Issue by anhquan0** [aws/studio-lab-examples#255] opened 2024-04-11 05:16 UTC
<img width="587" alt="image" src="https://github.com/aws/studio-lab-examples/assets/76616598/e4e94cce-c60f-4cca-8a0f-b24239c10681">
I tried with 3 of my email addresses, but when I registered, the information was like the photo above

 - OS: MacOS
 - Browser: Sidekick (Chromnium)

**Comment by CALEB789** [comment] 2024-04-13 08:04
the problem is the cors origin policy
![Capture](https://github.com/aws/studio-lab-examples/assets/58883113/5a13d679-959e-4455-b329-b0a8d1bfe510)
so what i did is i disabled the cors origin policy in chrome . this may not be the safest method but it works
Open Start window
Search Run and open it or press Window+ R
Paste chrome.exe --user-data-dir="C://Chrome dev session" --disable-web-security and execute it

**Comment by anhquan0** [comment] 2024-04-15 02:27
@CALEB789  This solution don't resolve this problem in my Macbook

**Comment by icoxfog417** [comment] 2024-04-15 02:37
Thank you for your patience. We have received several similar error reports, so let us confirm the cause.

https://github.com/aws/studio-lab-examples/issues/254

**Comment by CALEB789** [comment] 2024-04-15 06:29
@anhquan0 use this instead of that
open /Applications/Google\ Chrome.app --args --user-data-dir="/var/tmp/chrome-dev-disabled-security" --disable-web-security --disable-site-isolation-trials

**Comment by anhquan0** [comment] 2024-04-15 07:49
> open /Applications/Google\ Chrome.app --args --user-data-dir="/var/tmp/chrome-dev-disabled-security" --disable-web-security --disable-site-isolation-trials

I have the same error
<img width="1680" alt="image" src="https://github.com/aws/studio-lab-examples/assets/76616598/6a4e19d0-fd5a-4043-9c6c-f0b467b276d1">

**Comment by CALEB789** [comment] 2024-04-15 09:15
@anhquan0    then the problem is with your email address not the site

**Comment by icoxfog417** [comment] 2024-04-19 06:12
Thank you for your patience. We are investigating this issue. We would like to designate a single point of contact, therefore, we will be closing this issue. Please watch the following issue to monitor the progress.

https://github.com/aws/studio-lab-examples/issues/254

**Closed by icoxfog417** 2024-04-19 06:12 UTC
Labels: bug
