### ISSUE TITLE
Sign in page causes "Something went wrong" error and 403 ERROR

### ISSUE THREAD

**Issue by a6xi8tqqn** [aws/studio-lab-examples#184] opened 2022-12-26 07:12 UTC
I have trouble logging in sometimes

![1](https://user-images.githubusercontent.com/121421257/209516269-1a0a1b32-c7e2-4a82-bb25-0d776a14dea0.jpg)

Sometimes I face this problem

![2](https://user-images.githubusercontent.com/121421257/209516337-84f4560e-2258-4db9-b66c-39fb695cd5a9.jpg)

And after a lot of time it works fine

In the past it was very good

**Comment by bobbie7wei1998** [comment] 2022-12-29 22:00
Me and my college friends are having the same problem

**Comment by icoxfog417** [comment] 2023-01-02 13:51
Thank you for reporting the problem. To gather the another developer's feedback, we changed the issue title.
Does you college use proxy to access the internet? Sometimes 403 ERROR is caused by proxy.

**Comment by MicheleMonclova** [comment] 2023-01-05 22:03
Are you and your college friends all hitting the system at the same time from the same IP addresses? Can you tell me how many there are of you?

**Comment by junchuanwang** [comment] 2023-01-23 17:52
I am hitting this problem too.
<img width="1474" alt="Screen Shot 2023-01-23 at 9 52 07 AM" src="https://user-images.githubusercontent.com/52180478/214112990-947bd855-747d-467b-bf4d-8575eefd3e3f.png">

Not sure if this is because I haven't been using my account for a while

**Comment by junchuanwang** [comment] 2023-01-24 02:07
So I found it is indeed network problem.

The error can be clearer IMO

**Comment by icoxfog417** [comment] 2023-03-25 00:54
We close this issue because it caused by client side network problem.

**Closed by icoxfog417** 2023-03-25 00:54 UTC
Labels: bug
