### ISSUE TITLE
You can’t use the project runtime because your account is associated with activity that may have violated our Service Terms.You can’t use the project runtime because your account is associated with activity that may have violated our Service Terms.

### ISSUE THREAD

**Issue by 21066364-TanHuiZiOdelia** [aws/studio-lab-examples#89] opened 2022-03-17 02:26 UTC
**Describe the bug**
I'm facing this error when I try to start runtime: You can’t use the project runtime because your account is associated with activity that may have violated our Service Terms.

**To Reproduce**
1. Go to ''Login page and sign in"
2. Click on 'Start Runtime'
3. See error

**Expected behavior**
COU/GPU runtime should start.

**Screenshots**
![image](https://user-images.githubusercontent.com/95471166/158724009-c79af99e-32b0-4fac-bf09-7ca12ffc44a9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome

**Comment by hibxhhihey** [comment] 2022-03-17 07:22
I have this problem too.

**Comment by Wakfodo** [comment] 2022-03-17 07:40
yes, me too

**Comment by hibxhhihey** [comment] 2022-03-17 07:41
Have you solved the problem yet




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Risky ***@***.***&gt;; 
发送时间: 2022年3月17日(星期四) 下午3:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aws/studio-lab-examples] You can’t use the project runtime because your account is associated with activity that may have violated our Service Terms.You can’t use the project runtime because your account is associated with activity that may have violated our Service Terms. (Issue #89)





 
是的，我也是
 
-
 直接回复此电子邮件，在 GitHub 上查看或取消订阅。
使用适用于 iOS 或 Android 的 GitHub Mobile 随时随地对通知进行分类。
您收到此邮件是因为您发表了评论。Message ID: ***@***.***&gt;

**Comment by hibxhhihey** [comment] 2022-03-17 07:44
In the morning, I am doing experiments, and in the afternoon, I can't get in

**Comment by jnpm** [comment] 2022-03-17 08:28
I also have the same error message showing up.

**Comment by crazy-winds** [comment] 2022-03-17 10:06
I also have this problem. Did you solve it please?

**Comment by magdiemad5s** [comment] 2022-03-17 10:30
"i also have this problem" and they are like having the GitHub account right today
yall did violate the terms of service,i don't know what yall did but this is what you get and no there is no workaround that+new accounts that you make will get disabled/never get approved so good luck violating the rules again

**Comment by magdiemad5s** [comment] 2022-03-17 10:32
yall did violate the terms of service, i don't know what yall did but this is what you get and no there is no workaround that+new accounts that you make will get disabled/never get approved so good luck violating the rules again

**Comment by jnpm** [comment] 2022-03-17 10:45
Except that my studio lab usage was exclusively used for educational purposes and no service terms were violated.

**Comment by hibxhhihey** [comment] 2022-03-17 10:46
ME TOO



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月17日(星期四) 晚上6:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aws/studio-lab-examples] You can’t use the project runtime because your account is associated with activity that may have violated our Service Terms.You can’t use the project runtime because your account is associated with activity that may have violated our Service Terms. (Issue #89)





 
Except that my studio lab usage was exclusively used for educational purposes and no service terms were violated.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Chalili12** [comment] 2022-03-17 12:01
ME TOO

**Comment by Ben-Yee** [comment] 2022-03-17 12:15
Me too

**Comment by Ben-Yee** [comment] 2022-03-17 12:22
Except exclusively usage,I have no idea why my account got blocked.I never ever use it to mine cryptocurrency.And my work for my paper still on it.

**Comment by crazy-winds** [comment] 2022-03-17 12:44
Me too. The things I reproduced before are still on it, and I plan to make improvements, but suddenly I can't use it in the afternoon.

**Comment by hibxhhihey** [comment] 2022-03-18 00:37
everybody，this is aws's reply
'
Hello,
Thanks for your email. Your account was detected as creating an excessive amount of instance requests which is not permitted. We will reinstate your account but you need to stop programmatic requests for compute else you will be blocked again.
'

**Comment by alao556** [comment] 2022-03-18 03:51
> everybody，this is aws's reply ' Hello, Thanks for your email. Your account was detected as creating an excessive amount of instance requests which is not permitted. We will reinstate your account but you need to stop programmatic requests for compute else you will be blocked again. '

Thanks for your share. But when our account will be reinstated? I still cannot start runtime...

**Comment by MicheleMonclova** [comment] 2022-03-18 04:25
"Thank you all for communicating here. Yesterday we noticed some accounts making excessive GPU requests, and we had to block them. We will be managing this more gracefully in the future, and will be updating our FAQs to make it more clear that this is an unacceptable use of our service.
We are still in preview, so we appreciate your patience and your responsible usage.
We are looking into reinstating these accounts."

**Comment by hibxhhihey** [comment] 2022-03-18 06:29
I do not know




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月18日(星期五) 中午11:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aws/studio-lab-examples] You can’t use the project runtime because your account is associated with activity that may have violated our Service Terms.You can’t use the project runtime because your account is associated with activity that may have violated our Service Terms. (Issue #89)





  
everybody，this is aws's reply ' Hello, Thanks for your email. Your account was detected as creating an excessive amount of instance requests which is not permitted. We will reinstate your account but you need to stop programmatic requests for compute else you will be blocked again. '
  
Thanks for your share. But when our account will be reinstated? I still cannot start runtime...
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hibxhhihey** [comment] 2022-03-18 06:31
I really understand your hard work, but we are also eager to complete our project. We hope that you can introduce some standards or how many hours I can use it for a week. We really appreciate that you can let us use it for free, and we really need it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月18日(星期五) 中午12:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aws/studio-lab-examples] You can’t use the project runtime because your account is associated with activity that may have violated our Service Terms.You can’t use the project runtime because your account is associated with activity that may have violated our Service Terms. (Issue #89)





 
"Thank you all for communicating here. Yesterday we noticed some accounts making excessive GPU requests, and we had to block them. We will be managing this more gracefully in the future, and will be updating our FAQs to make it more clear that this is an unacceptable use of our service.
 We are still in preview, so we appreciate your patience and your responsible usage.
 We are looking into reinstating these accounts."
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by crazy-winds** [comment] 2022-03-18 07:50
I've been using the CPU for the last few days, why isn't it letting me use it.

**Comment by 21066364-TanHuiZiOdelia** [comment] 2022-03-19 04:07
> Thank you all for communicating here. Yesterday we noticed some accounts making excessive GPU requests, and we had to block them. We will be managing this more gracefully in the future, and will be updating our FAQs to make it more clear that this is an unacceptable use of our service. We are still in preview, so we appreciate your patience and your responsible usage. We are looking into reinstating these accounts. Michele Monclova SageMaker Studio Lab Service Team

Hi Michele,
Appreciate the fact that Amazon lets us use GPU for free. Do note that the excessive requests were due to "no runtime available now".

![image](https://user-images.githubusercontent.com/95471166/159106041-6ee61e57-d289-481c-b924-4267bd9744ec.png)

**Comment by icoxfog417** [comment] 2022-04-01 09:10
Dear @21066364-TanHuiZiOdelia , the message you faced is related to #88. It is different from your first error. If you already solve first violated Service Terms message, please close this issue and 👍 to #88 if you do not mind. The number of 👍 is the metrics of need in community and it affects our priority.

**Comment by austinlasseter** [comment] 2022-05-17 17:37
Any update on when GPU's will be available again? I am teaching a data science class for a bootcamp, and all students are using Sagemaker Studio Lab. Without GPU's we can't train deep learning models. Greatly appreciate your making this service available free of charge - but is there a timeline on when it might be fixed? Thank you

**Comment by icoxfog417** [comment] 2022-11-05 06:18
The major topic of this issue is the unavailability of Studio Lab that came from service term violation. We solve it so that I close this issue. Of course GPU instance error continues, we deal with it in another issue.

**Closed by icoxfog417** 2022-11-05 06:18 UTC
Labels: bug
