### ISSUE TITLE
Error loading Runtime/Project

### ISSUE THREAD

**Issue by czrnkp** [aws/studio-lab-examples#136] opened 2022-07-29 12:08 UTC
Attempting to start runtime/project, receive error "There was a problem when loading your project.  This should be resolved shortly.  Please try again later. This originally occurred yesterday (7/28) and is still occurring today (7/29).

Tried logging out, back in, same error.

See screenshot attached. 
<img width="1366" alt="Screen Shot 2022-07-29 at 7 39 27 AM" src="https://user-images.githubusercontent.com/17835548/181752352-13c8ad3e-d680-403f-ab0d-3c14757b175f.png">

**Comment by icoxfog417** [comment] 2022-07-30 03:13
Dear @czrnkp, sorry for the trouble that could not launch your project. I have encountered this problem too. The final solution I took was deleted the account then recreate the account. The email address was already approved so that the waiting time was short. If this solution is acceptable to you, please try it.

We are very glad if you let us know the procedures that you took until the error (~7/28). (In my case, after I created the new Kernel the error was occurred).

**Comment by czrnkp** [comment] 2022-07-30 10:15
Thank you, I deleted my account and resubmitted my account request.

**Comment by czrnkp** [comment] 2022-07-30 11:08
That worked, appreciate the help!

**Comment by icoxfog417** [comment] 2022-07-30 13:43
Your welcome! After confirming your project works fine, please close this issue.

**Comment by czrnkp** [comment] 2022-08-01 11:43
Issue resolved!  Deleted account, created new account under the same credentials.

**Closed** 2022-08-01 11:43 UTC
Labels: bug

**Comment by icoxfog417** [comment] 2022-08-01 13:48
Great! You are welcome and we continue to deal with the root cause.
