### ISSUE TITLE
Start runtime error

### ISSUE THREAD

**Issue by Skorp321** [aws/studio-lab-examples#117] opened 2022-06-08 06:19 UTC
When I try to run the runtime with cpu I get an error! How do I fix this?

![2022-06-08_09-13-26](https://user-images.githubusercontent.com/14059767/172545480-95857570-3847-4b4d-8fa6-2ec88acc0ed3.png)

**Comment by icoxfog417** [comment] 2022-06-08 08:59
@Skorp321 Thank you for using the Studio Lab and your feedback. We have already dealing with this issue. As temporary solution, please launch the instance by taking the interval. I confirmed that several trials lead to the success of launch.

**Comment by MicheleMonclova** [comment] 2022-06-14 21:10
@Skorp321 this issue is more likely due to the fact that your account was found to break one of the AWS Acceptable Use Policies or our restrictions outlined in our FAQ like crypto-mining or more than one account per email.

**Comment by Skorp321** [comment] 2022-06-18 18:46
I didn't do anything forbidden. I used only one account and purely for educational purposes! I don't understand why I was banned!?15.06.2022, 00:10, "MicheleMonclova" ***@***.***>:
@Skorp321 this issue is more likely due to the fact that your account was found to break one of the AWS Acceptable Use Policies or our restrictions outlined in our FAQ like crypto-mining or more than one account per email.

**Comment by icoxfog417** [comment] 2022-11-05 06:57
Dear @Skorp321 , we close this issue. Please let us know if you still have the trouble despite you do not violate the service term.

**Closed by icoxfog417** 2022-11-05 06:57 UTC
Labels: bug
